name: CI

on:
  push:
    branches: [main, 'mvbitfield-*']
  pull_request:
    branches: [main, 'mvbitfield-*']
  schedule:
    - cron: '0 16 * * 0'

env:
  CARGO_TERM_COLOR: always

jobs:
  stable:
    name: Stable Toolchain
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Prepare Rust stable toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy
      - name: Check formatting
        run: cargo +stable fmt --check
      - name: Check Clippy lints
        run: cargo +stable clippy --test clippy -- --deny warnings
      - name: Run tests
        run: cargo +stable test
      - name: Build docs
        run: cargo +stable doc -p mvbitfield --no-deps

  nightly:
    name: Nightly Toolchain
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Prepare Rust nightly toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          components: clippy, miri, rust-src, rustfmt
      - name: Check formatting
        run: cargo +nightly fmt --check
      - name: Check Clippy lints
        run: cargo +nightly clippy --test clippy --all-features -- --deny warnings
      - name: Run tests
        run: cargo +nightly test --all-features
      - name: Run Miri tests
        run: cargo +nightly miri test -p mvbitfield
      - name: Build docs
        run: cargo +nightly doc --all-features -p mvbitfield --no-deps
